### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Fady1114** [xertxa/Zyklon#29]
Visit http://localhost:1337 on your machine or http://192.168.x.x:1337 on an external device to use it.
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::1337
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at Function.listen (C:\Users\pc23\Desktop\4.0\bin\cloud\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\Users\pc23\Desktop\4.0\bin\cloud\app.js:104:5)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 1337

**Comment by Fady1114** [comment]
How do i fix this? i have set the java home thing etc.. i have correct version of jdk and i have node js

**Comment by mhmyesman** [comment]
Change the port you're running the web interface on - you can see that 1337 is already in use: 
``Error: listen EADDRINUSE: address already in use :::1337``

**Comment by Fady1114** [comment]
Yeah i tried and there isnt even anything with the port 1337 already in use

**Comment by mhmyesman** [comment]
You've tried switching ports? Same issue?

**Comment by Fady1114** [comment]
Yes same issue  same message and same error

**Comment by Fady1114** [comment]
It tells me to make sure im on forge i tried 1.7.10 forge recommended version and latest version and 1.8.9 forge recommended and latest all didnt work
