### ISSUE TITLE
Help please! thanks :)

### ISSUE THREAD

**Issue by Ecstasy666** [xertxa/Zyklon#7]
Starting cloud configuration server.
Visit http://localhost:1337 on your machine or http://192.168.x.x:1337 on an external device to use it.
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::1337
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1449:7)
    at Function.listen (D:\bin\cloud\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (D:\bin\cloud\app.js:104:5)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 1337
}

**Comment by xertxa** [comment]
do you use any razer software?

**Comment by stinke134** [comment]
Change the port as it’s alr in use
